### ISSUE TITLE
Ignoring Port 9000 traffic

### ISSUE THREAD

**Issue by BenHall** [kristian-lange/net-glimpse#2]
Firstly, this is a great idea!! 

However, I'm finding that if I expose the service then all of the output is net-glimpse websockets itself.

Is there a way to ignore traffic on port 9000?

**Comment by kristian-lange** [comment]
Thanks!

I saw this too. I will add a filter in net-glimps that let it filter out it's own traffic. And a parameter in the config to switch this filter on and off.

**Comment by kristian-lange** [comment]
I released version 1.3 that by default filters out net-glimpses own traffic (all the WebSocket packets). And it has a parameter -DskipOwnTraffic. If one still want this traffic set it to 'false'.

**Comment by BenHall** [comment]
Amazing!!! Thank you so much. I'll give it another go later today and see what the results are.
